# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\playfail.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 362)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.PlainText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PlainText.setGeometry(QtCore.QRect(110, 70, 531, 41))
        self.PlainText.setObjectName("PlainText")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 40, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.CipherText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.CipherText.setGeometry(QtCore.QRect(110, 230, 531, 51))
        self.CipherText.setObjectName("CipherText")
        self.Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Decrypt.setGeometry(QtCore.QRect(520, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Decrypt.setFont(font)
        self.Decrypt.setObjectName("Decrypt")
        self.KeyText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.KeyText.setGeometry(QtCore.QRect(110, 130, 161, 41))
        self.KeyText.setObjectName("KeyText")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 0, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 190, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Encrypt.setGeometry(QtCore.QRect(160, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Encrypt.setFont(font)
        self.Encrypt.setObjectName("Encrypt")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 230, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Matrix = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Matrix.setEnabled(False)
        self.Matrix.setGeometry(QtCore.QRect(290, 140, 351, 81))
        self.Matrix.setObjectName("Matrix")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Key"))
        self.label_5.setText(_translate("MainWindow", "TRƯƠNG THỊ NHƯ THUẬN - 2280603163"))
        self.Decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.label_4.setText(_translate("MainWindow", "Play Fail Cipher"))
        self.label_6.setText(_translate("MainWindow", "Matrix"))
        self.Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text"))
        self.label.setText(_translate("MainWindow", "Plain Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
